import { Hono } from 'hono'
import { z } from 'zod'
import { SessionCreateInputSchema } from '@panelito/types'
import { createServiceClient } from '../lib/supabase'
import { requireAuth, type AuthVariables } from '../middleware/auth'

// -----------------------------------------------------------------------
// Rate limiting (T-03-05, T-03-06)
// In-memory token buckets keyed by user ID or IP.
// Phase 1 uses in-memory; Redis-backed is post-MVP.
// -----------------------------------------------------------------------

interface TokenBucket {
  tokens: number
  lastRefill: number
}

const sessionCreateBuckets = new Map<string, TokenBucket>()
const guestJoinBuckets = new Map<string, TokenBucket>()

const MAX_SESSION_CREATES_PER_MINUTE = 10
const MAX_GUEST_JOINS_PER_MINUTE = 20
const MINUTE_MS = 60_000

function checkRateLimit(
  buckets: Map<string, TokenBucket>,
  key: string,
  maxPerMinute: number
): boolean {
  const now = Date.now()
  let bucket = buckets.get(key)

  if (!bucket) {
    bucket = { tokens: maxPerMinute - 1, lastRefill: now }
    buckets.set(key, bucket)
    return true
  }

  // Refill tokens if a minute has passed
  const elapsed = now - bucket.lastRefill
  if (elapsed >= MINUTE_MS) {
    bucket.tokens = maxPerMinute
    bucket.lastRefill = now
  }

  if (bucket.tokens <= 0) {
    return false // Rate limited
  }

  bucket.tokens--
  return true
}

// -----------------------------------------------------------------------
// Error helper (T-03-07)
// Wraps unexpected Supabase errors — no raw error messages leak to client.
// -----------------------------------------------------------------------

function toClientError(err: unknown): string {
  if (err instanceof Error) {
    // Log for server-side debugging only
    console.error('[sessions] Internal error:', err.message)
  }
  return 'internal'
}

// -----------------------------------------------------------------------
// Sessions router
// -----------------------------------------------------------------------

export const sessionsRouter = new Hono<{ Variables: AuthVariables }>()

/**
 * POST /api/sessions
 * Creates a new session for the authenticated creator.
 *
 * SESS-02: Creator creates session with title and mode.
 * The short_code is generated by the Postgres generate_short_code() function.
 *
 * Rate limit: max 10 creates/minute per user (T-03-05).
 */
sessionsRouter.post('/', requireAuth, async (c) => {
  const user = c.get('user')

  // T-03-05: per-user rate limit on session creation
  if (!checkRateLimit(sessionCreateBuckets, user.id, MAX_SESSION_CREATES_PER_MINUTE)) {
    return c.json({ error: 'rate_limited' }, 429)
  }

  let body: unknown
  try {
    body = await c.req.json()
  } catch {
    return c.json({ error: 'invalid_json' }, 400)
  }

  const parsed = SessionCreateInputSchema.safeParse(body)
  if (!parsed.success) {
    return c.json({ error: 'validation_error', issues: parsed.error.issues }, 400)
  }

  const supabase = createServiceClient()

  try {
    // short_code is generated by the DB trigger (generate_short_code() function).
    // We must call select('*') after insert to get the generated value.
    const { data, error } = await supabase
      .from('sessions')
      .insert({
        creator_id: user.id,
        title: parsed.data.title ?? null,
        mode: parsed.data.mode ?? null,
        short_code: await generateShortCodeViaRpc(supabase),
      })
      .select()
      .single()

    if (error) {
      console.error('[sessions] INSERT error:', error.message)
      return c.json({ error: toClientError(error) }, 500)
    }

    return c.json(data, 201)
  } catch (err) {
    return c.json({ error: toClientError(err) }, 500)
  }
})

/**
 * Generate a short code using the Postgres RPC function.
 * Falls back to an in-process generator if RPC fails.
 */
async function generateShortCodeViaRpc(
  supabase: ReturnType<typeof createServiceClient>
): Promise<string> {
  const { data, error } = await supabase.rpc('generate_short_code')
  if (error || !data) {
    // Fallback: generate in-process
    const alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
    return Array.from(
      { length: 6 },
      () => alphabet[Math.floor(Math.random() * alphabet.length)]!
    ).join('')
  }
  return data as string
}

/**
 * GET /api/sessions/:id
 * Returns the session for the authenticated user (creator or guest with anon token).
 *
 * Supabase anonymous tokens have aud: 'authenticated' so requireAuth
 * accepts both creator JWTs and guest anonymous JWTs.
 */
sessionsRouter.get('/:id', requireAuth, async (c) => {
  const { id } = c.req.param()
  const supabase = createServiceClient()

  try {
    const { data, error } = await supabase
      .from('sessions')
      .select('*')
      .eq('id', id)
      .single()

    if (error || !data) {
      return c.json({ error: 'not_found' }, 404)
    }

    return c.json(data, 200)
  } catch (err) {
    return c.json({ error: toClientError(err) }, 500)
  }
})

/**
 * POST /api/sessions/:id/freeze
 * Freezes the session. Only the creator can freeze.
 *
 * SESS-05: Creator can manually freeze session.
 * T-03-02: Non-creator gets 403; creator_id check is in addition to RLS.
 *
 * SESS-08: When session is frozen, guests cannot send messages
 * (RLS requires status = 'active' on messages INSERT).
 */
sessionsRouter.post('/:id/freeze', requireAuth, async (c) => {
  const { id } = c.req.param()
  const user = c.get('user')
  const supabase = createServiceClient()

  try {
    // Fetch the session first to verify creator_id (T-03-02)
    const { data: session, error: fetchError } = await supabase
      .from('sessions')
      .select('id, creator_id, status')
      .eq('id', id)
      .single()

    if (fetchError || !session) {
      return c.json({ error: 'not_found' }, 404)
    }

    // T-03-02: Elevation of Privilege protection
    if (session.creator_id !== user.id) {
      return c.json({ error: 'forbidden' }, 403)
    }

    const { data: updated, error: updateError } = await supabase
      .from('sessions')
      .update({ status: 'frozen' })
      .eq('id', id)
      .select()
      .single()

    if (updateError || !updated) {
      return c.json({ error: toClientError(updateError) }, 500)
    }

    return c.json(updated, 200)
  } catch (err) {
    return c.json({ error: toClientError(err) }, 500)
  }
})

/**
 * POST /api/sessions/:id/close
 * Closes the session. Only the creator can close.
 *
 * SESS-06: Creator can formally close/finalize session.
 * T-03-02: Non-creator gets 403.
 *
 * SESS-08: After session is closed, guest tokens cannot insert messages
 * (RLS policy requires status = 'active'). No extra teardown required
 * because the token itself remains valid — but RLS blocks writes.
 * Guest tokens auto-expire per Supabase anon token TTL (default 1h + refresh).
 */
sessionsRouter.post('/:id/close', requireAuth, async (c) => {
  const { id } = c.req.param()
  const user = c.get('user')
  const supabase = createServiceClient()

  try {
    // Fetch the session first to verify creator_id (T-03-02)
    const { data: session, error: fetchError } = await supabase
      .from('sessions')
      .select('id, creator_id, status')
      .eq('id', id)
      .single()

    if (fetchError || !session) {
      return c.json({ error: 'not_found' }, 404)
    }

    // T-03-02: Elevation of Privilege protection
    if (session.creator_id !== user.id) {
      return c.json({ error: 'forbidden' }, 403)
    }

    const { data: updated, error: updateError } = await supabase
      .from('sessions')
      .update({ status: 'closed' })
      .eq('id', id)
      .select()
      .single()

    if (updateError || !updated) {
      return c.json({ error: toClientError(updateError) }, 500)
    }

    return c.json(updated, 200)
  } catch (err) {
    return c.json({ error: toClientError(err) }, 500)
  }
})

/**
 * GET /api/sessions/by-code/:code
 * Public endpoint — no auth required.
 * Returns limited session info for the guest join landing page.
 *
 * T-03-03: Returns ONLY { id, title, creator_display_name, status }.
 * Does NOT return creator_id, encrypted_api_key, ai_response_count, etc.
 * The creator's display name is fetched from auth.users via the service client.
 */
sessionsRouter.get('/by-code/:code', async (c) => {
  const { code } = c.req.param()
  const supabase = createServiceClient()

  try {
    // T-03-03: Explicitly select ONLY safe fields — never return creator_id or encrypted fields
    const { data: session, error } = await supabase
      .from('sessions')
      .select('id, title, status, creator_id')
      .eq('short_code', code)
      .single()

    if (error || !session) {
      return c.json({ error: 'not_found' }, 404)
    }

    // Fetch creator's display name from auth.users via admin API
    let creatorDisplayName: string | null = null
    try {
      const { data: adminUser } = await supabase.auth.admin.getUserById(session.creator_id)
      creatorDisplayName =
        adminUser?.user?.user_metadata?.full_name ??
        adminUser?.user?.email ??
        null
    } catch {
      // Non-fatal: display name is best-effort
    }

    // T-03-03: Return only the safe subset — do NOT include creator_id
    return c.json({
      id: session.id,
      title: session.title,
      creator_display_name: creatorDisplayName,
      status: session.status,
    }, 200)
  } catch (err) {
    return c.json({ error: toClientError(err) }, 500)
  }
})

/**
 * POST /api/sessions/by-code/:code/guests
 * Issues an anonymous Supabase token for a guest joining a session.
 * Public endpoint — this IS the authentication endpoint for guests.
 *
 * SESS-04: Guests enter via join link with display name only, no registration.
 * SESS-10: Guest token is returned for localStorage persistence.
 * D-03: Guests can join even closed/frozen sessions (workspace shows read-only mode).
 *
 * Rate limit: max 20 guest joins/minute per IP (T-03-06).
 *
 * T-03-01: Anonymous tokens have a unique `sub` claim; RLS on messages INSERT
 * requires auth.uid() = author_id, so guests cannot impersonate each other.
 */
sessionsRouter.post('/by-code/:code/guests', async (c) => {
  const { code } = c.req.param()

  // T-03-06: per-IP rate limit on guest joins
  const clientIp = c.req.header('x-forwarded-for') ?? c.req.header('x-real-ip') ?? 'unknown'
  if (!checkRateLimit(guestJoinBuckets, clientIp, MAX_GUEST_JOINS_PER_MINUTE)) {
    return c.json({ error: 'rate_limited' }, 429)
  }

  const GuestJoinSchema = z.object({
    display_name: z.string().min(1).max(40).trim(),
  })

  let body: unknown
  try {
    body = await c.req.json()
  } catch {
    return c.json({ error: 'invalid_json' }, 400)
  }

  const parsed = GuestJoinSchema.safeParse(body)
  if (!parsed.success) {
    return c.json({ error: 'validation_error', issues: parsed.error.issues }, 400)
  }

  const supabase = createServiceClient()

  try {
    // Look up session by code (D-03: guests can join closed/frozen sessions)
    const { data: session, error: sessionError } = await supabase
      .from('sessions')
      .select('id, title, status')
      .eq('short_code', code)
      .single()

    if (sessionError || !session) {
      return c.json({ error: 'not_found' }, 404)
    }

    // Mint a fresh anonymous Supabase user for the guest (SESS-04)
    // signInAnonymously() creates a new user in auth.users with aud: 'authenticated'
    const { data: anonData, error: anonError } = await supabase.auth.signInAnonymously()

    if (anonError || !anonData.user || !anonData.session) {
      console.error('[sessions] signInAnonymously error:', anonError?.message)
      return c.json({ error: 'internal' }, 500)
    }

    return c.json({
      session_id: session.id,
      guest_user_id: anonData.user.id,
      access_token: anonData.session.access_token,
      refresh_token: anonData.session.refresh_token,
      display_name: parsed.data.display_name,
    }, 201)
  } catch (err) {
    return c.json({ error: toClientError(err) }, 500)
  }
})

export default sessionsRouter
